import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation dictionary
const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    pricing: 'Pricing',
    dashboard: 'Dashboard',
    login: 'Login',
    signUp: 'Sign Up',
    logout: 'Logout',
    // gallery: 'Gallery',
    autoAgent: 'Agent',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Change Background Now',
    aiCvGenerator: 'AI CV Generator',
    colorPaletteGenerator: 'Color Palette Generator',
    objectDetectionTool: 'Object Detection Tool',
    imageUpscaler: 'Image Upscaler',
    backgroundBlur: 'Background Blur',
    imageEditingSuite: 'Image Editing Suite',
    faceDetection: 'Face Detection & Cropping',
    imageMetadataAnalyzer: 'Image Metadata Analyzer',
    formatConverter: 'Format Converter',
    aiAutoAgent: 'AI Auto Agent',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Advanced background removal, enhancement, and manipulation tools',
    createProfessionalCvs: 'Create professional CVs with AI-powered content generation',
    extractAndGenerate: 'Extract and generate beautiful color palettes from images',
    identifyAndLocate: 'Identify and locate objects in images with precision',
    enhanceImageResolution: 'Enhance image resolution with AI-powered upscaling',
    applyProfessionalPortrait: 'Apply professional portrait mode effects to images',
    advancedImageEditing: 'Advanced image editing tools including cropping, blurring, rotation, and flipping',
    detectFacesAndAutomatically: 'Detect faces and automatically crop to optimal dimensions',
    extractDetailedExif: 'Extract detailed EXIF data and image information',
    convertBetweenImage: 'Convert between image formats with smart compression',
    uploadImageAndTell: 'Upload an image and tell AI what to do - our smart agent processes your request automatically',
    
    // Watermark removal
    watermarkRemoval: 'Watermark Removal',
    removeWatermark: 'Remove Background',
    removeWatermarkDescription: 'Remove watermarks from your generated images',
    loginRequired: 'Login Required',
    loginToAccessWatermarkRemoval: 'Please log in to access watermark removal service',
    
    // General
    welcome: 'Welcome',
    hi: 'Hi',
    pro: 'PRO',
    worldClassAISolutions: 'World-class AI solutions. Transform your workflow.',
    exploreOurSuite: 'Explore our AI services designed to enhance your productivity.',
    serviceCategories: 'Service Categories',
    imageProcessing: 'Image Processing',
    advancedTools: 'Advanced tools for image enhancement, background removal, and manipulation.',
    contentGeneration: 'Content Generation',
    aiPoweredTools: 'AI-powered tools for creating professional content and documents.',
    designTools: 'Design Tools',
    creativeTools: 'Creative tools for designers and artists to enhance their workflows.',
    readyToGetStarted: 'Ready to Get Started?',
    joinThousands: 'Join thousands of professionals using our AI platform to enhance their productivity and creativity.',
    createFreeAccount: 'Create Free Account',
    viewPricing: 'View Pricing',
    explore: 'Explore →',
    allServices: 'All Services',
    accounts: 'Account',
    dashboardLink: 'Dashboard',
    apiKeys: 'API Keys',
    pricingLink: 'Pricing',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    security: 'Security',
    compliance: 'Compliance',
    allRightsReserved: 'All rights reserved.',
    
    // Authentication
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    signInToYourAccount: 'Sign in to your account',
    dontHaveAnAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    alreadyHaveAnAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    registerForFree: 'Register for Free',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember me',
    signingIn: 'Signing in...',
    newToPlatform: 'New to AI Background Removal?',
    createAccount: 'Create a new account',
    iAgreeToThe: 'I agree to the',
    and: 'and',
    termsAndConditions: 'Terms and Conditions',
    creatingAccount: 'Creating account...',
    chooseFile: 'Choose File',
    whatShouldAIDo: 'What should the AI do?',
    removeBackgroundExample: 'Remove the background',
    changeBackgroundExample: 'Change background to blue',
    enhanceImageExample: 'Enhance the image quality',
    vibrantColorsExample: 'Make the colors more vibrant',
    changeBackgroundAndEnhanceExample: 'Change background to #FF6B6B and enhance',
    instructionPlaceholder: "Examples: 'Remove the background', 'Change background to blue', 'Make the person wear a red shirt', 'Enhance the image quality', 'Make the colors more vibrant', 'Change the person's shirt to red and the background to green', etc.",
    instructionDescription: 'Describe what you want to do with the image in natural language. The AI will analyze your request and apply the appropriate processing. You can request multiple operations in a single instruction.',
    processWithAI: 'Process with AI',
    reset: 'Reset',
    processingWithAI: 'Processing your image with AI...',
    original: 'Original',
    processed: 'Processed',
    downloadResult: 'Download Result',
    allImages: 'All Images',
    backgroundRemoval: 'Background Removal',
    backgroundChange: 'Background Change',
    backgroundReplace: 'Background Replace',
    clothesChange: 'Clothes Change',
    clothesReplace: 'Clothes Replace',
    saveYourWork: 'Save Your Work',
    createAccountToSave: 'Create an account to save and access your processed images anytime',
    noImagesFound: 'No images found',
    processImagesToSee: 'Process some images to see them appear here',
    tryServicesToSee: 'Try our services to see your results here',
    tryOurServices: 'Try Our Services',
    readyToProcess: 'Ready to Process Your Images?',
    startUsingAIPowered: 'Start using our AI-powered image processing tools today - no account required to get started!',
    startProcessing: 'Start Processing',
    pricing: 'Pricing',
    free: 'Free',
    forever: 'forever',
    perfectForGettingStarted: 'Perfect for getting started with our AI platform',
    basicImageProcessing: 'Basic Image Processing',
    apiCallsPerDay: 'API calls/day',
    standardSupport: 'Standard Support',
    proFeatures: 'Pro Features',
    prioritySupport: 'Priority Support',
    unlimitedApiCalls: 'Unlimited API calls',
    getStarted: 'Get Started',
    pro: 'Pro',
    perMonth: '/month',
    idealForProfessionals: 'Ideal for professionals and small teams',
    allFreeFeatures: 'All Free Features',
    advancedImageProcessing: 'Advanced Image Processing',
    aiUpscaler: 'AI Upscaler',
    faceDetection: 'Face Detection',
    objectDetection: 'Object Detection',
    metadataAnalyzer: 'Metadata Analyzer',
    formatConverter: 'Format Converter',
    upgradeToPro: 'Upgrade to Pro',
    enterprise: 'Enterprise',
    custom: 'Custom',
    forLargeTeams: 'For large teams and custom requirements',
    allProFeatures: 'All Pro Features',
    customApiLimits: 'Custom API limits',
    dedicatedSupport: 'Dedicated Support',
    customIntegrations: 'Custom Integrations',
    slaGuarantee: 'SLA Guarantee',
    teamManagement: 'Team Management',
    advancedAnalytics: 'Advanced Analytics',
    whiteLabelOptions: 'White-label Options',
    customAiModels: 'Custom AI Models',
    contactSales: 'Contact Sales',
    mostPopular: 'MOST POPULAR',
    featureComparison: 'Feature Comparison',
    feature: 'Feature',
    unlimited: 'Unlimited',
    limited: 'Limited',
    readyToTransform: 'Ready to Transform Your Workflow?',
    startFreeTrial: 'Start Free Trial',
    exploreServices: 'Explore Services',
    brandName: 'Hintergrund entfernen',

    // Buttons
    submit: 'Submit',
    upload: 'Upload',
    process: 'Process',
    cancel: 'Cancel',
    
    // Errors
    error: 'Error',
    success: 'Success',
    pleaseTryAgain: 'Please try again',
    
    // Footer
    servicesFooter: 'Services',
    legal: 'Legal',
    accountFooter: 'Account',

    // Language
    language: 'Language',

    // Watermark removal
    watermarkRemoval: 'Watermark Removal',
    removeWatermarkDescription: 'Remove watermarks from your generated images',
    loginRequired: 'Login Required',
    loginToAccessWatermarkRemoval: 'Please log in to access watermark removal service',
    uploadImage: 'Upload Image',
    chooseDifferentImage: 'Choose a different image',
    dragAndDrop: 'Drag & drop your image here',
    maxFileSize: 'Max file size: 10MB. Supported formats: JPG, PNG, GIF',
    browseFiles: 'Browse Files',
    processing: 'Processing...',
    download: 'Download',
    newImage: 'New Image',
    result: 'Result',
    watermarkSuccessfullyRemoved: 'Watermark successfully removed!',
    processedImageWillAppear: 'Processed image will appear here',
    processImageToSeeResult: 'Process an image to see the result here',
    howItWorks: 'How it works',
    uploadImageDescription: 'Upload your image with watermark',
    removeWatermarkDescription: 'Click the remove watermark button',
    downloadResultDescription: 'Download your watermark-free image',
    fileTooLarge: 'File is too large. Maximum size is 10MB.',
    invalidFileType: 'Invalid file type. Please upload an image file.',
    pleaseSelectFile: 'Please select a file to process.',
    errorProcessingImage: 'Error processing image. Please try again.',

    // Additional translations for homepage
    before: 'Before',
    after: 'After',
    beforeAfterComparison: 'Before and after comparison',
    whyChoosePlatform: 'Why Choose Our AI Platform?',
    lightningFastProcessing: 'Lightning Fast Processing',
    getResultsInSeconds: 'Get results in seconds with our optimized AI algorithms',
    enterpriseSecurity: 'Enterprise Security',
    militaryGradeEncryption: 'Military-grade encryption keeps your data safe and secure',
    accuracy: '99.9% Accuracy',
    precisionAI: 'Precision AI technology delivers professional-quality results',
    support: 'Support',
    quality: 'Quality',
    seoTitle: 'Free Background Remover - Professional AI Tool for Perfect Images',
    seoDescription: 'Remove backgrounds for free! Use our AI to precisely remove backgrounds in seconds. Ideal for professionals & beginners. Start now online!',
    altBefore: 'Original photo before background removal',
    altAfter: 'Processed photo with background removed by AI',
    brandName: 'Hintergrund entfernen',
    seoContentH1: 'Professional Background Removal Made Easy',
    seoContentP1: 'Our innovative AI tool makes removing backgrounds easier than ever. Whether for e-commerce, private snapshots, or professional design projects – isolate your main subject precisely and quickly with just one click. Manual clipping is a thing of the past, as our AI detects fine details like hair or complex edges automatically.',
    seoContentH2_1: 'Why Professional Background Removal is Crucial',
    seoContentP2: 'In today\'s visual world, first impressions are everything. A clean, transparent background makes your products look higher quality and focuses the customer\'s attention on the essentials. Efficient background removal saves valuable time in post-processing and allows you to use your graphics flexibly across various channels. From Instagram posts to professional catalogs – the possibilities are endless.',
    seoContentH2_2: 'How our Tool Works for Perfect Results',
    seoContentP3: 'Removing backgrounds online requires no technical knowledge with us. Simply upload your desired image in JPG, PNG, or WebP format. Our powerful AI analyzes the photo in seconds and delivers a perfect result with a transparent background. You can download the image immediately or add a new, creative background. Our goal is to provide you with a tool that combines high precision with maximum speed, so you can focus entirely on your creativity. Start now and experience how easy modern background removal can be!',
    keywords: [
      'hintergrund entfernen kostenlos',
      'hintergrund entfernen bild',
      'hintergrund entfernen online',
      'hintergrund entfernen photoshop',
      'hintergrund entfernen kostenlos online',
      'hintergrund entfernen png',
      'Hintergründe aus Bildern entfernen'
    ],
    faqTitle: 'Frequently Asked Questions (FAQ) - Remove Background',
    faqs: [
      {
        question: 'What is Hintergrund entfernen?',
        answer: 'Hintergrund entfernen is an AI-powered tool that allows you to remove backgrounds from your photos quickly and precisely. It’s ideal for e-commerce, portraits, and creative projects.'
      },
      {
        question: 'How do I remove the background of a photo?',
        answer: 'Simply upload your image to our platform. Our advanced AI automatically detects the main subject and removes the background within seconds.'
      },
      {
        question: 'Is it free to use?',
        answer: 'Yes, we offer a free basic version that allows you to remove backgrounds and achieve high-quality results. For additional features, we also offer Pro plans.'
      },
      {
        question: 'Which file formats are supported?',
        answer: 'We support all common formats such as JPG, PNG, JPEG, and WebP.'
      },
      {
        question: 'How long does it take to process a photo?',
        answer: 'Thanks to our optimized AI algorithms, processing usually takes less than 5 seconds.'
      },
      {
        question: 'Can I process multiple photos at once?',
        answer: 'In our current version, we process photos individually to ensure maximum precision. However, we are constantly working on new features.'
      },
      {
        question: 'How do I save my edited photos?',
        answer: 'Once processing is complete, you can click the "Download" button to save your photo with a transparent background in PNG format.'
      },
      {
        question: 'Is there a mobile app for Hintergrund entfernen?',
        answer: 'Hintergrund entfernen is optimized for web use and works excellently on all mobile browsers, so no app installation is required.'
      },
      {
        question: 'Are my uploaded photos safe?',
        answer: 'Yes, security is our top priority. Your photos are transmitted encrypted and automatically deleted from our servers after processing.'
      },
      {
        question: 'How do I contact support?',
        answer: 'If you have questions or suggestions, you can reach our support team via the contact form on our website.'
      }
    ],
  },
  es: {
    // Navigation
    home: 'Inicio',
    services: 'Servicios',
    pricing: 'Precios',
    dashboard: 'Panel',
    login: 'Iniciar Sesión',
    signUp: 'Registrarse',
    logout: 'Cerrar Sesión',
    gallery: 'Galería',
    autoAgent: 'Agente',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Cambiar Fondo Ahora',
    aiCvGenerator: 'Generador de CV con IA',
    colorPaletteGenerator: 'Generador de Paleta de Colores',
    objectDetectionTool: 'Herramienta de Detección de Objetos',
    imageUpscaler: 'Mejorador de Imágenes',
    backgroundBlur: 'Desenfoque de Fondo',
    imageEditingSuite: 'Suite de Edición de Imágenes',
    faceDetection: 'Detección y Recorte de Rostros',
    imageMetadataAnalyzer: 'Analizador de Metadatos de Imágenes',
    formatConverter: 'Convertidor de Formatos',
    aiAutoAgent: 'Agente Automático de IA',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Herramientas avanzadas de eliminación de fondo, mejora y manipulación',
    createProfessionalCvs: 'Crea CV profesionales con generación de contenido impulsada por IA',
    extractAndGenerate: 'Extrae y genera hermosas paletas de colores a partir de imágenes',
    identifyAndLocate: 'Identifica y localiza objetos en imágenes con precisión',
    enhanceImageResolution: 'Mejora la resolución de imágenes con escalado impulsado por IA',
    applyProfessionalPortrait: 'Aplica efectos de modo retrato profesional a las imágenes',
    advancedImageEditing: 'Herramientas avanzadas de edición de imágenes incluyendo recorte, desenfoque, rotación y volteo',
    detectFacesAndAutomatically: 'Detecta rostros y recorta automáticamente a dimensiones óptimas',
    extractDetailedExif: 'Extrae datos EXIF detallados e información de la imagen',
    convertBetweenImage: 'Convierte entre formatos de imagen con compresión inteligente',
    uploadImageAndTell: 'Sube una imagen y dile a la IA qué hacer - nuestro agente inteligente procesa tu solicitud automáticamente',
    
    // Watermark removal
    watermarkRemoval: 'Eliminación de Marca de Agua',
    removeWatermark: 'Eliminar Fondo',
    removeWatermarkDescription: 'Elimina marcas de agua de tus imágenes generadas',
    loginRequired: 'Inicio de Sesión Requerido',
    loginToAccessWatermarkRemoval: 'Por favor inicia sesión para acceder al servicio de eliminación de marca de agua',
    
    // General
    welcome: 'Bienvenido',
    hi: 'Hola',
    pro: 'PRO',
    worldClassAISolutions: 'Soluciones de IA de clase mundial para empresas. Transforma tu flujo de trabajo con inteligencia artificial de vanguardia.',
    exploreOurSuite: 'Explora nuestra completa suite de servicios de IA diseñados para resolver problemas del mundo real y mejorar tu productividad.',
    serviceCategories: 'Categorías de Servicio',
    imageProcessing: 'Procesamiento de Imágenes',
    advancedTools: 'Herramientas avanzadas para mejora de imágenes, eliminación de fondo y manipulación.',
    contentGeneration: 'Generación de Contenido',
    aiPoweredTools: 'Herramientas impulsadas por IA para crear contenido y documentos profesionales.',
    designTools: 'Herramientas de Diseño',
    creativeTools: 'Herramientas creativas para diseñadores y artistas para mejorar sus flujos de trabajo.',
    readyToGetStarted: '¿Listo para Empezar?',
    joinThousands: 'Únete a miles de profesionales que utilizan nuestra plataforma de IA para mejorar su productividad y creatividad.',
    createFreeAccount: 'Crear Cuenta Gratis',
    viewPricing: 'Ver Precios',
    explore: 'Explorar →',
    allServices: 'Todos los Servicios',
    accounts: 'Cuenta',
    dashboardLink: 'Panel',
    apiKeys: 'Claves de API',
    pricingLink: 'Precios',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    security: 'Seguridad',
    compliance: 'Cumplimiento',
    allRightsReserved: 'Todos los derechos reservados.',
    
    // Authentication
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    signInToYourAccount: 'Inicia sesión en tu cuenta',
    dontHaveAnAccount: '¿No tienes una cuenta?',
    signUpHere: 'Regístrate aquí',
    alreadyHaveAnAccount: '¿Ya tienes una cuenta?',
    signInHere: 'Inicia sesión aquí',
    registerForFree: 'Registrarse Gratis',
    forgotPassword: '¿Olvidaste tu contraseña?',
    rememberMe: 'Recuérdame',
    signingIn: 'Iniciando sesión...',
    newToPlatform: '¿Nuevo en AI Background Removal?',
    createAccount: 'Crear una nueva cuenta',
    iAgreeToThe: 'Acepto los',
    and: 'y',
    termsAndConditions: 'Términos y Condiciones',
    creatingAccount: 'Creando cuenta...',
    chooseFile: 'Elegir archivo',
    whatShouldAIDo: '¿Qué debe hacer la IA?',
    removeBackgroundExample: 'Eliminar el fondo',
    changeBackgroundExample: 'Cambiar fondo a azul',
    enhanceImageExample: 'Mejorar la calidad de la imagen',
    vibrantColorsExample: 'Hacer los colores más vibrantes',
    changeBackgroundAndEnhanceExample: 'Cambiar fondo a #FF6B6B y mejorar',
    instructionPlaceholder: "Ejemplos: 'Eliminar el fondo', 'Cambiar fondo a azul', 'Hacer que la persona use una camisa roja', 'Mejorar la calidad de la imagen', 'Hacer los colores más vibrantes', 'Cambiar la camisa de la persona a rojo y el fondo a verde', etc.",
    instructionDescription: 'Describe lo que quieres hacer con la imagen en lenguaje natural. La IA analizará tu solicitud y aplicará el procesamiento apropiado. Puedes solicitar múltiples operaciones en una sola instrucción.',
    processWithAI: 'Procesar con IA',
    reset: 'Reiniciar',
    processingWithAI: 'Procesando tu imagen con IA...',
    original: 'Original',
    processed: 'Procesado',
    downloadResult: 'Descargar Resultado',
    allImages: 'Todas las Imágenes',
    backgroundRemoval: 'Eliminación de Fondo',
    backgroundChange: 'Cambio de Fondo',
    backgroundReplace: 'Reemplazo de Fondo',
    clothesChange: 'Cambio de Ropa',
    clothesReplace: 'Reemplazo de Ropa',
    saveYourWork: 'Guarda Tu Trabajo',
    createAccountToSave: 'Crea una cuenta para guardar y acceder a tus imágenes procesadas en cualquier momento',
    noImagesFound: 'No se encontraron imágenes',
    processImagesToSee: 'Procesa algunas imágenes para que aparezcan aquí',
    tryServicesToSee: 'Prueba nuestros servicios para ver tus resultados aquí',
    tryOurServices: 'Prueba Nuestros Servicios',
    readyToProcess: '¿Listo para Procesar Tus Imágenes?',
    startUsingAIPowered: '¡Comienza a usar nuestras herramientas de procesamiento de imágenes impulsadas por IA hoy mismo: no se requiere cuenta para comenzar!',
    startProcessing: 'Comenzar a Procesar',
    pricing: 'Precios',
    free: 'Gratis',
    forever: 'para siempre',
    perfectForGettingStarted: 'Perfecto para comenzar con nuestra plataforma de IA',
    basicImageProcessing: 'Procesamiento Básico de Imágenes',
    apiCallsPerDay: 'Llamadas a la API/día',
    standardSupport: 'Soporte Estándar',
    proFeatures: 'Funciones Pro',
    prioritySupport: 'Soporte Prioritario',
    unlimitedApiCalls: 'Llamadas a la API ilimitadas',
    getStarted: 'Empezar',
    pro: 'Pro',
    perMonth: '/mes',
    idealForProfessionals: 'Ideal para profesionales y equipos pequeños',
    allFreeFeatures: 'Todas las Funciones Gratuitas',
    advancedImageProcessing: 'Procesamiento Avanzado de Imágenes',
    aiUpscaler: 'Mejorador de IA',
    faceDetection: 'Detección Facial',
    objectDetection: 'Detección de Objetos',
    metadataAnalyzer: 'Analizador de Metadatos',
    formatConverter: 'Convertidor de Formato',
    upgradeToPro: 'Actualizar a Pro',
    enterprise: 'Empresarial',
    custom: 'Personalizado',
    forLargeTeams: 'Para equipos grandes y requisitos personalizados',
    allProFeatures: 'Todas las Funciones Pro',
    customApiLimits: 'Límites de API personalizados',
    dedicatedSupport: 'Soporte Dedicado',
    customIntegrations: 'Integraciones Personalizadas',
    slaGuarantee: 'Garantía de SLA',
    teamManagement: 'Gestión de Equipos',
    advancedAnalytics: 'Análisis Avanzado',
    whiteLabelOptions: 'Opciones de marca blanca',
    customAiModels: 'Modelos de IA Personalizados',
    contactSales: 'Contactar Ventas',
    mostPopular: 'MÁS POPULAR',
    featureComparison: 'Comparación de Funciones',
    feature: 'Función',
    unlimited: 'Ilimitado',
    limited: 'Limitado',
    readyToTransform: '¿Listo para Transformar Tu Flujo de Trabajo?',
    startFreeTrial: 'Comenzar Prueba Gratuita',
    exploreServices: 'Explorar Servicios',
    brandName: 'Hintergrund entfernen',

    // Buttons
    submit: 'Enviar',
    upload: 'Subir',
    process: 'Procesar',
    cancel: 'Cancelar',
    
    // Errors
    error: 'Error',
    success: 'Éxito',
    pleaseTryAgain: 'Por favor intenta de nuevo',
    
    // Footer
    servicesFooter: 'Servicios',
    legal: 'Legal',
    accountFooter: 'Cuenta',

    // Language
    language: 'Idioma',

    // Watermark removal
    watermarkRemoval: 'Eliminación de Marca de Agua',
    removeWatermarkDescription: 'Elimina marcas de agua de tus imágenes generadas',
    loginRequired: 'Inicio de Sesión Requerido',
    loginToAccessWatermarkRemoval: 'Por favor inicia sesión para acceder al servicio de eliminación de marca de agua',
    uploadImage: 'Subir Imagen',
    chooseDifferentImage: 'Elegir una imagen diferente',
    dragAndDrop: 'Arrastra y suelta tu imagen aquí',
    maxFileSize: 'Tamaño máximo de archivo: 10MB. Formatos soportados: JPG, PNG, GIF',
    browseFiles: 'Explorar Archivos',
    processing: 'Procesando...',
    download: 'Descargar',
    newImage: 'Nueva Imagen',
    result: 'Resultado',
    watermarkSuccessfullyRemoved: '¡Marca de agua eliminada con éxito!',
    processedImageWillAppear: 'La imagen procesada aparecerá aquí',
    processImageToSeeResult: 'Procesa una imagen para ver el resultado aquí',
    howItWorks: 'Cómo funciona',
    uploadImageDescription: 'Sube tu imagen con marca de agua',
    removeWatermarkDescription: 'Haz clic en el botón de eliminar marca de agua',
    downloadResultDescription: 'Descarga tu imagen sin marca de agua',
    fileTooLarge: 'El archivo es demasiado grande. El tamaño máximo es 10MB.',
    invalidFileType: 'Tipo de archivo inválido. Por favor sube un archivo de imagen.',
    pleaseSelectFile: 'Por favor selecciona un archivo para procesar.',
    errorProcessingImage: 'Error al procesar la imagen. Por favor intenta de nuevo.',

    // Additional translations for homepage
    before: 'Antes',
    after: 'Después',
    beforeAfterComparison: 'Comparación antes y después',
    whyChoosePlatform: '¿Por qué elegir nuestra plataforma de IA?',
    lightningFastProcessing: 'Procesamiento ultrarrápido',
    getResultsInSeconds: 'Obtenga resultados en segundos con nuestros algoritmos de IA optimizados',
    enterpriseSecurity: 'Seguridad empresarial',
    militaryGradeEncryption: 'Cifrado de grado militar mantiene sus datos seguros',
    accuracy: 'Precisión del 99.9%',
    precisionAI: 'La tecnología de IA de precisión entrega resultados de calidad profesional',
    support: 'Soporte',
    quality: 'Calidad',
    seoTitle: 'Quitar fondo gratis - Herramienta IA para imágenes perfectas',
    seoDescription: '¡Quitar fondo gratis ahora! Con nuestra IA, elimina fondos con precisión en segundos. Ideal para profesionales y principiantes. ¡Empieza online!',
    altBefore: 'Foto original antes de quitar el fondo',
    altAfter: 'Foto procesada con fondo quitado por IA',
    brandName: 'Hintergrund entfernen',
    seoContentH1: 'Eliminar el fondo de forma profesional es fácil',
    seoContentP1: 'Nuestra innovadora herramienta de IA hace que eliminar fondos sea más fácil que nunca. Ya sea para comercio electrónico, fotos privadas o proyectos de diseño profesional: aísle su tema principal con precisión und rapidez con un solo clic. El recorte manual es cosa del pasado, ya que nuestra IA detecta automáticamente detalles finos como el cabello o bordes complejos.',
    seoContentH2_1: 'Por qué es crucial eliminar el fondo de forma profesional',
    seoContentP2: 'En el mundo visual de hoy, la primera impresión lo es todo. Un fondo limpio und transparente hace que sus productos se vean de mayor calidad und enfoca la atención del cliente en lo esencial. La eliminación eficiente del fondo ahorra tiempo valioso en el posprocesamiento und le permite utilizar sus gráficos de manera flexible en varios canales. Desde publicaciones de Instagram hasta catálogos profesionales: las posibilidades son infinitas.',
    seoContentH2_2: 'Cómo funciona nuestra herramienta para obtener resultados perfectos',
    seoContentP3: 'Eliminar fondos online no requiere conocimientos técnicos con nosotros. Simplemente suba su imagen deseada en formato JPG, PNG o WebP. Nuestra potente IA analiza la foto en segundos und ofrece un resultado perfecto con un fondo transparente. Puede descargar la imagen de inmediato o agregar un fondo nuevo und creativo. Nuestro objetivo es brindarle una herramienta que combine alta precisión con la máxima velocidad, para que pueda concentrarse por completo en su creatividad. ¡Empiece ahora und experimente lo fácil que puede ser eliminar fondos modernos!',
    keywords: [
      'hintergrund entfernen kostenlos',
      'hintergrund entfernen bild',
      'hintergrund entfernen online',
      'hintergrund entfernen photoshop',
      'hintergrund entfernen kostenlos online',
      'hintergrund entfernen png',
      'Hintergründe aus Bildern entfernen'
    ],
    faqTitle: 'Preguntas Frecuentes (FAQ) - Eliminar Fondo',
    faqs: [
      {
        question: '¿Qué es Hintergrund entfernen?',
        answer: 'Hintergrund entfernen es una herramienta impulsada por IA que te permite eliminar fondos de tus fotos de forma rápida y precisa. Es ideal para comercio electrónico, retratos y proyectos creativos.'
      },
      {
        question: '¿Cómo elimino el fondo de una foto?',
        answer: 'Simplemente sube tu imagen a nuestra plataforma. Nuestra IA avanzada detecta automáticamente el sujeto principal y elimina el fondo en cuestión de segundos.'
      },
      {
        question: '¿Es de uso gratuito?',
        answer: 'Sí, ofrecemos una versión básica gratuita que te permite eliminar fondos y obtener resultados de alta calidad. Para funciones adicionales, también ofrecemos planes Pro.'
      },
      {
        question: '¿Qué formatos de archivo son compatibles?',
        answer: 'Soportamos todos los formatos comunes como JPG, PNG, JPEG y WebP.'
      },
      {
        question: '¿Cuánto tiempo se tarda en procesar una foto?',
        answer: 'Gracias a nuestros algoritmos de IA optimizados, el procesamiento suele tardar menos de 5 segundos.'
      },
      {
        question: '¿Puedo procesar varias fotos a la vez?',
        answer: 'En nuestra versión actual, procesamos las fotos individualmente para garantizar la máxima precisión. Sin embargo, estamos trabajando constantemente en nuevas funciones.'
      },
      {
        question: '¿Cómo guardo mis fotos editadas?',
        answer: 'Una vez finalizado el procesamiento, puedes hacer clic en el botón "Descargar" para guardar tu foto con fondo transparente en formato PNG.'
      },
      {
        question: '¿Existe una aplicación móvil para Hintergrund entfernen?',
        answer: 'Hintergrund entfernen está optimizado para su uso en la web y funciona excelentemente en todos los navegadores móviles, por lo que no es necesario instalar ninguna aplicación.'
      },
      {
        question: '¿Son seguras mis fotos subidas?',
        answer: 'Sí, la seguridad es nuestra prioridad. Tus fotos se transmiten encriptadas y se eliminan automáticamente de nuestros servidores después del procesamiento.'
      },
      {
        question: '¿Cómo me pongo en contacto con el soporte?',
        answer: 'Si tienes preguntas o sugerencias, puedes comunicarte con nuestro equipo de soporte a través del formulario de contacto en nuestro sitio web.'
      }
    ],
  },
  de: {
    // Navigation
    home: 'Startseite',
    services: 'Dienste',
    pricing: 'Preise',
    dashboard: 'Dashboard',
    login: 'Anmelden',
    signUp: 'Registrieren',
    logout: 'Abmelden',
    gallery: 'Galerie',
    autoAgent: 'Agent',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Hintergrund jetzt ändern',
    aiCvGenerator: 'KI Lebenslauf-Generator',
    colorPaletteGenerator: 'Farbpaletten-Generator',
    objectDetectionTool: 'Objekterkennung-Tool',
    imageUpscaler: 'Bild-Scaler',
    backgroundBlur: 'Hintergrundunschärfe',
    imageEditingSuite: 'Bildbearbeitungs-Suite',
    faceDetection: 'Gesichtserkennung & Zuschneiden',
    imageMetadataAnalyzer: 'Bild-Metadaten-Analysator',
    formatConverter: 'Format-Konverter',
    aiAutoAgent: 'KI Auto-Agent',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Fortgeschrittene Werkzeuge zur Hintergrundentfernung, Verbesserung und Manipulation',
    createProfessionalCvs: 'Erstellen Sie professionelle Lebensläufe mit KI-gestützter Inhaltserstellung',
    extractAndGenerate: 'Extrahieren und generieren Sie schöne Farbpaletten aus Bildern',
    identifyAndLocate: 'Identifizieren und lokalisieren Sie Objekte in Bildern mit Präzision',
    enhanceImageResolution: 'Verbessern Sie die Bildauflösung mit KI-gestütztem Upscaling',
    applyProfessionalPortrait: 'Wenden Sie professionelle Porträt-Modus-Effekte auf Bilder an',
    advancedImageEditing: 'Fortgeschrittene Bildbearbeitungstools einschließlich Zuschneiden, Unschärfen, Drehen und Spiegeln',
    detectFacesAndAutomatically: 'Erkennen Sie Gesichter und schneiden Sie diese automatisch auf optimale Dimensionen zu',
    extractDetailedExif: 'Extrahieren Sie detaillierte EXIF-Daten und Bildinformationen',
    convertBetweenImage: 'Konvertieren Sie zwischen Bildformaten mit intelligenter Komprimierung',
    uploadImageAndTell: 'Laden Sie ein Bild hoch und sagen Sie der KI, was zu tun ist - unser intelligenter Agent verarbeitet Ihre Anfrage automatisch',
    
    // Watermark removal
    watermarkRemoval: 'Wasserzeichenentfernung',
    removeWatermark: 'Hintergrund entfernen',
    removeWatermarkDescription: 'Entfernen Sie Wasserzeichen aus Ihren generierten Bildern',
    loginRequired: 'Anmeldung erforderlich',
    loginToAccessWatermarkRemoval: 'Bitte melden Sie sich an, um auf den Wasserzeichenentfernungsdienst zuzugreifen',
    
    // General
    welcome: 'Willkommen',
    hi: 'Hallo',
    pro: 'PRO',
    worldClassAISolutions: 'Weltklasse KI-Lösungen.',
    exploreOurSuite: 'Entdecken Sie unsere KI-Dienste zur Steigerung Ihrer Produktivität.',
    serviceCategories: 'Dienstleistungskategorien',
    imageProcessing: 'Bildverarbeitung',
    advancedTools: 'Fortgeschrittene Tools zur Bildverbesserung, Hintergrundentfernung und Manipulation.',
    contentGeneration: 'Inhaltsgenerierung',
    aiPoweredTools: 'KI-gestützte Tools zur Erstellung professioneller Inhalte und Dokumente.',
    designTools: 'Design-Tools',
    creativeTools: 'Kreative Tools für Designer und Künstler, um ihre Arbeitsabläufe zu verbessern.',
    readyToGetStarted: 'Bereit loszulegen?',
    joinThousands: 'Tausende von Fachleuten nutzen unsere KI-Plattform, um Produktivität und Kreativität zu steigern.',
    createFreeAccount: 'Kostenloses Konto erstellen',
    viewPricing: 'Preise ansehen',
    explore: 'Entdecken →',
    allServices: 'Alle Dienste',
    accounts: 'Konto',
    dashboardLink: 'Dashboard',
    apiKeys: 'API-Schlüssel',
    pricingLink: 'Preise',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    security: 'Sicherheit',
    compliance: 'Compliance',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    
    // Authentication
    email: 'E-Mail',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    signInToYourAccount: 'Melden Sie sich bei Ihrem Konto an',
    dontHaveAnAccount: 'Sie haben noch kein Konto?',
    signUpHere: 'Hier registrieren',
    alreadyHaveAnAccount: 'Sie haben bereits ein Konto?',
    signInHere: 'Hier anmelden',
    registerForFree: 'Kostenlos registrieren',
    forgotPassword: 'Passwort vergessen?',
    rememberMe: 'Angemeldet bleiben',
    signingIn: 'Anmeldung läuft...',
    newToPlatform: 'Neu bei AI Background Removal?',
    createAccount: 'Ein neues Konto erstellen',
    iAgreeToThe: 'Ich stimme den',
    and: 'und',
    termsAndConditions: 'Allgemeinen Geschäftsbedingungen',
    creatingAccount: 'Konto wird erstellt...',
    chooseFile: 'Datei auswählen',
    whatShouldAIDo: 'Was soll die KI tun?',
    removeBackgroundExample: 'Hintergrund entfernen',
    changeBackgroundExample: 'Hintergrund auf blau ändern',
    enhanceImageExample: 'Bildqualität verbessern',
    vibrantColorsExample: 'Farben lebendiger machen',
    changeBackgroundAndEnhanceExample: 'Hintergrund zu #FF6B6B ändern und verbessern',
    instructionPlaceholder: "Beispiele: 'Hintergrund entfernen', 'Hintergrund auf blau ändern', 'Person ein rotes Hemd anziehen', 'Bildqualität verbessern', 'Farben lebendiger machen', 'Hemd der Person rot und Hintergrund grün färben', etc.",
    instructionDescription: 'Beschreiben Sie in natürlicher Sprache, was Sie mit dem Bild tun möchten. Die KI analysiert Ihre Anfrage und wendet die entsprechende Verarbeitung an. Sie können mehrere Operationen in einer einzigen Anweisung anfordern.',
    processWithAI: 'Mit KI verarbeiten',
    reset: 'Zurücksetzen',
    processingWithAI: 'Ihr Bild wird mit KI verarbeitet...',
    original: 'Original',
    processed: 'Verarbeitet',
    downloadResult: 'Ergebnis herunterladen',
    allImages: 'Alle Bilder',
    backgroundRemoval: 'Hintergrundentfernung',
    backgroundChange: 'Hintergrundänderung',
    backgroundReplace: 'Hintergrundaustausch',
    clothesChange: 'Kleidungswechsel',
    clothesReplace: 'Kleidungsaustausch',
    saveYourWork: 'Speichern Sie Ihre Arbeit',
    createAccountToSave: 'Erstellen Sie ein Konto, um Ihre bearbeiteten Bilder jederzeit zu speichern und abzurufen',
    noImagesFound: 'Keine Bilder gefunden',
    processImagesToSee: 'Bearbeiten Sie einige Bilder, damit sie hier erscheinen',
    tryServicesToSee: 'Probieren Sie unsere Dienste aus, um Ihre Ergebnisse hier zu sehen',
    tryOurServices: 'Probieren Sie Unsere Dienste',
    readyToProcess: 'Bereit Ihre Bilder zu bearbeiten?',
    startUsingAIPowered: 'Beginnen Sie noch heute mit unseren KI-gestützten Bildbearbeitungstools - es ist kein Konto erforderlich, um zu starten!',
    startProcessing: 'Mit Bearbeitung Beginnen',
    pricing: 'Preise',
    free: 'Kostenlos',
    forever: 'für immer',
    perfectForGettingStarted: 'Perfekt, um mit unserer KI-Plattform zu beginnen',
    basicImageProcessing: 'Basis-Bildverarbeitung',
    apiCallsPerDay: 'API-Aufrufe/Tag',
    standardSupport: 'Standard-Support',
    proFeatures: 'Pro-Funktionen',
    prioritySupport: 'Priorisierter Support',
    unlimitedApiCalls: 'Unbegrenzte API-Aufrufe',
    getStarted: 'Loslegen',
    pro: 'Pro',
    perMonth: '/Monat',
    idealForProfessionals: 'Ideal für Fachleute und kleine Teams',
    allFreeFeatures: 'Alle kostenlosen Funktionen',
    advancedImageProcessing: 'Erweiterte Bildverarbeitung',
    aiUpscaler: 'KI-Scaler',
    faceDetection: 'Gesichtserkennung',
    objectDetection: 'Objekterkennung',
    metadataAnalyzer: 'Metadaten-Analysator',
    formatConverter: 'Format-Konverter',
    upgradeToPro: 'Auf Pro upgraden',
    enterprise: 'Enterprise',
    custom: 'Individuell',
    forLargeTeams: 'Für große Teams und individuelle Anforderungen',
    allProFeatures: 'Alle Pro-Funktionen',
    customApiLimits: 'Individuelle API-Limits',
    dedicatedSupport: 'Dedizierter Support',
    customIntegrations: 'Individuelle Integrationen',
    slaGuarantee: 'SLA-Garantie',
    teamManagement: 'Team-Management',
    advancedAnalytics: 'Erweiterte Analysen',
    whiteLabelOptions: 'White-Label-Optionen',
    customAiModels: 'Individuelle KI-Modelle',
    contactSales: 'Vertrieb kontaktieren',
    mostPopular: 'AM BELIEBTESTEN',
    featureComparison: 'Funktionsvergleich',
    feature: 'Funktion',
    unlimited: 'Unbegrenzt',
    limited: 'Begrenzt',
    readyToTransform: 'Bereit, Ihren Arbeitsablauf zu transformieren?',
    startFreeTrial: 'Kostenlose Testversion starten',
    exploreServices: 'Dienste erkunden',
    brandName: 'Hintergrund entfernen',
    seoContentH1: 'Professionelles Hintergrundentfernen leicht gemacht',
    seoContentP1: 'Unser innovatives KI-Tool macht das Hintergrundentfernen so einfach wie nie zuvor. Egal ob für den E-Commerce, private Schnappschüsse oder professionelle Design-Projekte – mit nur einem Klick isolieren Sie Ihr Hauptmotiv präzise und schnell. Das manuelle Ausschneiden gehört der Vergangenheit an, denn unsere künstliche Intelligenz erkennt feinste Details wie Haare oder komplexe Kanten vollautomatisch. Dies spart Ihnen nicht nur Zeit, sondern garantiert auch eine Qualität, die sonst nur Profi-Grafiker mit stundenlanger Arbeit erreichen würden.',
    seoContentH2_1: 'Warum die professionelle Hintergrundentfernung entscheidend ist',
    seoContentP2: 'In der heutigen visuellen Welt ist der erste Eindruck alles. Ein sauberer, transparenter Hintergrund lässt Ihre Produkte hochwertiger wirken und lenkt den Fokus der Kunden direkt auf das Wesentliche. Durch effizientes Hintergrundentfernen sparen Sie wertvolle Zeit in der Nachbearbeitung und können Ihre Grafiken flexibel auf verschiedenen Kanälen einsetzen. Von Instagram-Posts bis hin zu professionellen Katalogen – die Einsatzmöglichkeiten sind grenzenlos. Ein neutraler Hintergrund ist zudem die Basis für ein konsistentes Branding, das Vertrauen bei Ihrer Zielgruppe schafft und Ihre Marke nachhaltig stärkt.',
    seoContentH2_2: 'So einfach funktioniert unser Tool für perfekte Ergebnisse',
    seoContentP3: 'Das Online-Hintergrundentfernen erfordert bei uns keine technischen Vorkenntnisse. Laden Sie einfach Ihr gewünschtes Bild im Format JPG, PNG oder WebP hoch. Unsere leistungsstarke KI analysiert das Foto in Sekundenbruchteilen und liefert Ihnen ein perfektes Ergebnis mit transparentem Hintergrund. Danach können Sie das Bild sofort herunterladen oder einen neuen, kreativen Hintergrund hinzufügen. Unser Ziel ist es, Ihnen ein Werkzeug an die Hand zu geben, das höchste Präzision mit maximaler Geschwindigkeit vereint, damit Sie sich ganz auf Ihre Kreativität konzentrieren können. Dabei legen wir größten Wert auf Datenschutz: Ihre hochgeladenen Bilder werden verschlüsselt verarbeitet und nach der Bearbeitung automatisch gelöscht. Starten Sie jetzt und erleben Sie, wie mühelos modernes Hintergrundentfernen sein kann! Profitieren Sie von einer Technologie, die ständig weiterentwickelt wird, um Ihnen immer die besten Resultate am Markt zu bieten.',
    keywords: [
      'hintergrund entfernen kostenlos',
      'hintergrund entfernen bild',
      'hintergrund entfernen online',
      'hintergrund entfernen photoshop',
      'hintergrund entfernen kostenlos online',
      'hintergrund entfernen png',
      'Hintergründe aus Bildern entfernen',
      'Bild freistellen',
      'Foto Hintergrund löschen',
      'KI Hintergrundentferner'
    ],
    seoTitle: 'Kostenlos Hintergrundentfernen - KI-Tool für perfekte Bilder',
    seoDescription: 'Jetzt kostenlos Hintergrundentfernen! Mit unserer KI entfernen Sie Hintergründe präzise in Sekunden. Ideal für Profis & Einsteiger. Starten Sie jetzt online!',
    altBefore: 'Originalfoto vor dem Hintergrundentfernen',
    altAfter: 'Bearbeitetes Foto mit entferntem Hintergrund durch KI',
    faqTitle: 'Häufig gestellte Fragen (FAQ) - Hintergrund entfernen',
    faqs: [
      {
        question: 'Was ist Hintergrund entfernen?',
        answer: 'Hintergrund entfernen ist ein KI-gestütztes Tool, mit dem Sie Hintergründe aus Ihren Fotos schnell und präzise entfernen können. Es ist ideal für E-Commerce, Porträts und kreative Projekte.'
      },
      {
        question: 'Wie entferne ich den Hintergrund eines Fotos?',
        answer: 'Laden Sie einfach Ihr Bild auf unserer Plattform hoch. Unsere fortschrittliche KI erkennt das Hauptmotiv automatisch und entfernt den Hintergrund innerhalb von Sekunden.'
      },
      {
        question: 'Ist die Nutzung kostenlos?',
        answer: 'Ja, wir bieten eine kostenlose Basisversion an, mit der Sie Hintergründe entfernen und hochwertige Ergebnisse erzielen können. Für zusätzliche Funktionen bieten wir auch Pro-Pläne an.'
      },
      {
        question: 'Welche Dateiformate werden unterstützt?',
        answer: 'Wir unterstützen alle gängigen Formate wie JPG, PNG, JPEG und WebP.'
      },
      {
        question: 'Wie lange dauert es, ein Foto zu bearbeiten?',
        answer: 'Dank unserer optimierten KI-Algorithmen dauert die Bearbeitung in der Regel weniger als 5 Sekunden.'
      },
      {
        question: 'Kann ich mehrere Fotos gleichzeitig bearbeiten?',
        answer: 'In unserer aktuellen Version bearbeiten wir Fotos einzeln, um maximale Präzision zu gewährleisten. Wir arbeiten jedoch ständig an neuen Funktionen.'
      },
      {
        question: 'Wie speichere ich meine bearbeiteten Fotos?',
        answer: 'Sobald die Bearbeitung abgeschlossen ist, können Sie auf die Schaltfläche "Herunterladen" klicken, um Ihr Foto mit transparentem Hintergrund im PNG-Format zu speichern.'
      },
      {
        question: 'Gibt es eine mobile App für Hintergrund entfernen?',
        answer: 'Hintergrund entfernen ist für die Nutzung im Web optimiert und funktioniert hervorragend auf allen mobilen Browsern, sodass keine App-Installation erforderlich ist.'
      },
      {
        question: 'Sind meine hochgeladenen Fotos sicher?',
        answer: 'Ja, Sicherheit hat bei uns oberste Priorität. Ihre Fotos werden verschlüsselt übertragen und nach der Bearbeitung automatisch von unseren Servern gelöscht.'
      },
      {
        question: 'Wie kontaktiere ich den Support?',
        answer: 'Wenn Sie Fragen oder Anregungen haben, können Sie unser Support-Team über das Kontaktformular auf unserer Website erreichen.'
      }
    ],

    // Buttons
    submit: 'Senden',
    upload: 'Hochladen',
    process: 'Verarbeiten',
    cancel: 'Abbrechen',
    
    // Errors
    error: 'Fehler',
    success: 'Erfolg',
    pleaseTryAgain: 'Bitte versuchen Sie es erneut',
    
    // Footer
    servicesFooter: 'Dienste',
    legal: 'Rechtliches',
    accountFooter: 'Konto',

    // Language
    language: 'Sprache',

    // Watermark removal
    watermarkRemoval: 'Wasserzeichenentfernung',
    removeWatermarkDescription: 'Entfernen Sie Wasserzeichen aus Ihren generierten Bildern',
    loginRequired: 'Anmeldung erforderlich',
    loginToAccessWatermarkRemoval: 'Bitte melden Sie sich an, um auf den Wasserzeichenentfernungsdienst zuzugreifen',
    uploadImage: 'Bild hochladen',
    chooseDifferentImage: 'Anderes Bild wählen',
    dragAndDrop: 'Ziehen Sie Ihr Bild hierher',
    maxFileSize: 'Maximale Dateigröße: 10MB. Unterstützte Formate: JPG, PNG, GIF',
    browseFiles: 'Dateien durchsuchen',
    processing: 'Verarbeitung...',
    download: 'Herunterladen',
    newImage: 'Neues Bild',
    result: 'Ergebnis',
    watermarkSuccessfullyRemoved: 'Wasserzeichen erfolgreich entfernt!',
    processedImageWillAppear: 'Verarbeitetes Bild wird hier angezeigt',
    processImageToSeeResult: 'Verarbeiten Sie ein Bild, um das Ergebnis hier zu sehen',
    howItWorks: 'So funktioniert es',
    uploadImageDescription: 'Laden Sie Ihr Bild mit Wasserzeichen hoch',
    removeWatermarkDescription: 'Klicken Sie auf die Schaltfläche zum Entfernen des Wasserzeichens',
    downloadResultDescription: 'Laden Sie Ihr wasserzeichenfreies Bild herunter',
    fileTooLarge: 'Datei ist zu groß. Maximale Größe beträgt 10MB.',
    invalidFileType: 'Ungültiger Dateityp. Bitte laden Sie eine Bilddatei hoch.',
    pleaseSelectFile: 'Bitte wählen Sie eine Datei zum Verarbeiten aus.',
    errorProcessingImage: 'Fehler beim Verarbeiten des Bildes. Bitte versuchen Sie es erneut.',

    // Additional translations for homepage
    before: 'Vorher',
    after: 'Nachher',
    beforeAfterComparison: 'Vorher-Nachher-Vergleich',
    whyChoosePlatform: 'Warum unsere KI-Plattform wählen?',
    lightningFastProcessing: 'Blitzschnelle Verarbeitung',
    getResultsInSeconds: 'Erhalten Sie Ergebnisse in Sekunden mit unseren optimierten KI-Algorithmen',
    enterpriseSecurity: 'Unternehmenssicherheit',
    militaryGradeEncryption: 'Militärverschlüsselung schützt Ihre Daten',
    accuracy: '99,9 % Genauigkeit',
    precisionAI: 'Präzisions-KI-Technologie liefert professionelle Ergebnisse',
    support: 'Support',
    quality: 'Qualität',

    // Auto Agent Page
    aiAutoAgentTitle: 'KI Auto-Agent',
    aiAutoAgentDescription: 'Laden Sie ein Bild hoch und geben Sie der KI Anweisungen in natürlicher Sprache. Unser intelligenter Agent analysiert Ihre Anfrage und führt die entsprechenden Bildverarbeitungsaufgaben aus.',
    imagePreviewAlt: 'Vorschau',
    remove: 'Entfernen',
    clickToUpload: 'Klicken Sie zum Hochladen eines Bildes',
    supportedFormats: 'PNG, JPG, JPEG (Max. 10MB)',
    imageProcessedSuccessfully: 'Bild erfolgreich verarbeitet!',
    errorProcessingImage: 'Fehler bei der Bildverarbeitung. Bitte versuchen Sie es erneut.',
    selectValidImage: 'Bitte wählen Sie eine gültige Bilddatei aus',
    selectImageFirst: 'Bitte wählen Sie zuerst ein Bild aus',
    enterInstruction: 'Bitte geben Sie eine Anweisung ein',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('de');

  // Skip localStorage persistence to ensure German is always the default
  // and no user-selected language overrides it.
  
  const t = (key) => {
    const translation = translations[language]?.[key];
    return translation || key; // Fallback to the key if translation is not found
  };

  const value = {
    language,
    setLanguage,
    t,
    availableLanguages: ['en', 'es', 'de']
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};