import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation dictionary
const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    pricing: 'Pricing',
    dashboard: 'Dashboard',
    login: 'Login',
    signUp: 'Sign Up',
    logout: 'Logout',
    gallery: 'Gallery',
    autoAgent: 'Agent',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Change Background Now',
    aiCvGenerator: 'AI CV Generator',
    colorPaletteGenerator: 'Color Palette Generator',
    objectDetectionTool: 'Object Detection Tool',
    imageUpscaler: 'Image Upscaler',
    backgroundBlur: 'Background Blur',
    imageEditingSuite: 'Image Editing Suite',
    faceDetection: 'Face Detection & Cropping',
    imageMetadataAnalyzer: 'Image Metadata Analyzer',
    formatConverter: 'Format Converter',
    aiAutoAgent: 'AI Auto Agent',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Advanced background removal, enhancement, and manipulation tools',
    createProfessionalCvs: 'Create professional CVs with AI-powered content generation',
    extractAndGenerate: 'Extract and generate beautiful color palettes from images',
    identifyAndLocate: 'Identify and locate objects in images with precision',
    enhanceImageResolution: 'Enhance image resolution with AI-powered upscaling',
    applyProfessionalPortrait: 'Apply professional portrait mode effects to images',
    advancedImageEditing: 'Advanced image editing tools including cropping, blurring, rotation, and flipping',
    detectFacesAndAutomatically: 'Detect faces and automatically crop to optimal dimensions',
    extractDetailedExif: 'Extract detailed EXIF data and image information',
    convertBetweenImage: 'Convert between image formats with smart compression',
    uploadImageAndTell: 'Upload an image and tell AI what to do - our smart agent processes your request automatically',
    
    // Watermark removal
    watermarkRemoval: 'Watermark Removal',
    removeWatermark: 'Remove Background',
    removeWatermarkDescription: 'Remove watermarks from your generated images',
    loginRequired: 'Login Required',
    loginToAccessWatermarkRemoval: 'Please log in to access watermark removal service',
    
    // General
    welcome: 'Welcome',
    hi: 'Hi',
    pro: 'PRO',
    worldClassAISolutions: 'World-class AI solutions for enterprise businesses. Transform your workflow with cutting-edge artificial intelligence.',
    exploreOurSuite: 'Explore our comprehensive suite of AI services designed to solve real-world problems and enhance your productivity.',
    serviceCategories: 'Service Categories',
    imageProcessing: 'Image Processing',
    advancedTools: 'Advanced tools for image enhancement, background removal, and manipulation.',
    contentGeneration: 'Content Generation',
    aiPoweredTools: 'AI-powered tools for creating professional content and documents.',
    designTools: 'Design Tools',
    creativeTools: 'Creative tools for designers and artists to enhance their workflows.',
    readyToGetStarted: 'Ready to Get Started?',
    joinThousands: 'Join thousands of professionals using our AI platform to enhance their productivity and creativity.',
    createFreeAccount: 'Create Free Account',
    viewPricing: 'View Pricing',
    explore: 'Explore →',
    allServices: 'All Services',
    accounts: 'Account',
    dashboardLink: 'Dashboard',
    apiKeys: 'API Keys',
    pricingLink: 'Pricing',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    security: 'Security',
    compliance: 'Compliance',
    allRightsReserved: 'All rights reserved.',
    
    // Authentication
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    signInToYourAccount: 'Sign in to your account',
    dontHaveAnAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    alreadyHaveAnAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    registerForFree: 'Register for Free',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember me',
    signingIn: 'Signing in...',
    newToPlatform: 'New to AI Background Removal?',
    createAccount: 'Create a new account',
    iAgreeToThe: 'I agree to the',
    and: 'and',
    termsAndConditions: 'Terms and Conditions',
    creatingAccount: 'Creating account...',
    chooseFile: 'Choose File',
    whatShouldAIDo: 'What should the AI do?',
    removeBackgroundExample: 'Remove the background',
    changeBackgroundExample: 'Change background to blue',
    enhanceImageExample: 'Enhance the image quality',
    vibrantColorsExample: 'Make the colors more vibrant',
    changeBackgroundAndEnhanceExample: 'Change background to #FF6B6B and enhance',
    instructionPlaceholder: "Examples: 'Remove the background', 'Change background to blue', 'Make the person wear a red shirt', 'Enhance the image quality', 'Make the colors more vibrant', 'Change the person's shirt to red and the background to green', etc.",
    instructionDescription: 'Describe what you want to do with the image in natural language. The AI will analyze your request and apply the appropriate processing. You can request multiple operations in a single instruction.',
    processWithAI: 'Process with AI',
    reset: 'Reset',
    processingWithAI: 'Processing your image with AI...',
    original: 'Original',
    processed: 'Processed',
    downloadResult: 'Download Result',
    allImages: 'All Images',
    backgroundRemoval: 'Background Removal',
    backgroundChange: 'Background Change',
    backgroundReplace: 'Background Replace',
    clothesChange: 'Clothes Change',
    clothesReplace: 'Clothes Replace',
    saveYourWork: 'Save Your Work',
    createAccountToSave: 'Create an account to save and access your processed images anytime',
    noImagesFound: 'No images found',
    processImagesToSee: 'Process some images to see them appear here',
    tryServicesToSee: 'Try our services to see your results here',
    tryOurServices: 'Try Our Services',
    readyToProcess: 'Ready to Process Your Images?',
    startUsingAIPowered: 'Start using our AI-powered image processing tools today - no account required to get started!',
    startProcessing: 'Start Processing',
    pricing: 'Pricing',
    free: 'Free',
    forever: 'forever',
    perfectForGettingStarted: 'Perfect for getting started with our AI platform',
    basicImageProcessing: 'Basic Image Processing',
    apiCallsPerDay: 'API calls/day',
    standardSupport: 'Standard Support',
    proFeatures: 'Pro Features',
    prioritySupport: 'Priority Support',
    unlimitedApiCalls: 'Unlimited API calls',
    getStarted: 'Get Started',
    pro: 'Pro',
    perMonth: '/month',
    idealForProfessionals: 'Ideal for professionals and small teams',
    allFreeFeatures: 'All Free Features',
    advancedImageProcessing: 'Advanced Image Processing',
    aiUpscaler: 'AI Upscaler',
    faceDetection: 'Face Detection',
    objectDetection: 'Object Detection',
    metadataAnalyzer: 'Metadata Analyzer',
    formatConverter: 'Format Converter',
    upgradeToPro: 'Upgrade to Pro',
    enterprise: 'Enterprise',
    custom: 'Custom',
    forLargeTeams: 'For large teams and custom requirements',
    allProFeatures: 'All Pro Features',
    customApiLimits: 'Custom API limits',
    dedicatedSupport: 'Dedicated Support',
    customIntegrations: 'Custom Integrations',
    slaGuarantee: 'SLA Guarantee',
    teamManagement: 'Team Management',
    advancedAnalytics: 'Advanced Analytics',
    whiteLabelOptions: 'White-label Options',
    customAiModels: 'Custom AI Models',
    contactSales: 'Contact Sales',
    mostPopular: 'MOST POPULAR',
    featureComparison: 'Feature Comparison',
    feature: 'Feature',
    unlimited: 'Unlimited',
    limited: 'Limited',
    readyToTransform: 'Ready to Transform Your Workflow?',
    startFreeTrial: 'Start Free Trial',
    exploreServices: 'Explore Services',
    brandName: 'Hintergrund entfernen',

    // Buttons
    submit: 'Submit',
    upload: 'Upload',
    process: 'Process',
    cancel: 'Cancel',
    
    // Errors
    error: 'Error',
    success: 'Success',
    pleaseTryAgain: 'Please try again',
    
    // Footer
    servicesFooter: 'Services',
    legal: 'Legal',
    accountFooter: 'Account',

    // Language
    language: 'Language',

    // Watermark removal
    watermarkRemoval: 'Watermark Removal',
    removeWatermarkDescription: 'Remove watermarks from your generated images',
    loginRequired: 'Login Required',
    loginToAccessWatermarkRemoval: 'Please log in to access watermark removal service',
    uploadImage: 'Upload Image',
    chooseDifferentImage: 'Choose a different image',
    dragAndDrop: 'Drag & drop your image here',
    maxFileSize: 'Max file size: 10MB. Supported formats: JPG, PNG, GIF',
    browseFiles: 'Browse Files',
    processing: 'Processing...',
    download: 'Download',
    newImage: 'New Image',
    result: 'Result',
    watermarkSuccessfullyRemoved: 'Watermark successfully removed!',
    processedImageWillAppear: 'Processed image will appear here',
    processImageToSeeResult: 'Process an image to see the result here',
    howItWorks: 'How it works',
    uploadImageDescription: 'Upload your image with watermark',
    removeWatermarkDescription: 'Click the remove watermark button',
    downloadResultDescription: 'Download your watermark-free image',
    fileTooLarge: 'File is too large. Maximum size is 10MB.',
    invalidFileType: 'Invalid file type. Please upload an image file.',
    pleaseSelectFile: 'Please select a file to process.',
    errorProcessingImage: 'Error processing image. Please try again.',

    // Additional translations for homepage
    before: 'Before',
    after: 'After',
    beforeAfterComparison: 'Before and after comparison',
    whyChoosePlatform: 'Why Choose Our AI Platform?',
    lightningFastProcessing: 'Lightning Fast Processing',
    getResultsInSeconds: 'Get results in seconds with our optimized AI algorithms',
    enterpriseSecurity: 'Enterprise Security',
    militaryGradeEncryption: 'Military-grade encryption keeps your data safe and secure',
    accuracy: '99.9% Accuracy',
    precisionAI: 'Precision AI technology delivers professional-quality results',
    support: 'Support',
  },
  es: {
    // Navigation
    home: 'Inicio',
    services: 'Servicios',
    pricing: 'Precios',
    dashboard: 'Panel',
    login: 'Iniciar Sesión',
    signUp: 'Registrarse',
    logout: 'Cerrar Sesión',
    gallery: 'Galería',
    autoAgent: 'Agente',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Cambiar Fondo Ahora',
    aiCvGenerator: 'Generador de CV con IA',
    colorPaletteGenerator: 'Generador de Paleta de Colores',
    objectDetectionTool: 'Herramienta de Detección de Objetos',
    imageUpscaler: 'Mejorador de Imágenes',
    backgroundBlur: 'Desenfoque de Fondo',
    imageEditingSuite: 'Suite de Edición de Imágenes',
    faceDetection: 'Detección y Recorte de Rostros',
    imageMetadataAnalyzer: 'Analizador de Metadatos de Imágenes',
    formatConverter: 'Convertidor de Formatos',
    aiAutoAgent: 'Agente Automático de IA',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Herramientas avanzadas de eliminación de fondo, mejora y manipulación',
    createProfessionalCvs: 'Crea CV profesionales con generación de contenido impulsada por IA',
    extractAndGenerate: 'Extrae y genera hermosas paletas de colores a partir de imágenes',
    identifyAndLocate: 'Identifica y localiza objetos en imágenes con precisión',
    enhanceImageResolution: 'Mejora la resolución de imágenes con escalado impulsado por IA',
    applyProfessionalPortrait: 'Aplica efectos de modo retrato profesional a las imágenes',
    advancedImageEditing: 'Herramientas avanzadas de edición de imágenes incluyendo recorte, desenfoque, rotación y volteo',
    detectFacesAndAutomatically: 'Detecta rostros y recorta automáticamente a dimensiones óptimas',
    extractDetailedExif: 'Extrae datos EXIF detallados e información de la imagen',
    convertBetweenImage: 'Convierte entre formatos de imagen con compresión inteligente',
    uploadImageAndTell: 'Sube una imagen y dile a la IA qué hacer - nuestro agente inteligente procesa tu solicitud automáticamente',
    
    // Watermark removal
    watermarkRemoval: 'Eliminación de Marca de Agua',
    removeWatermark: 'Eliminar Fondo',
    removeWatermarkDescription: 'Elimina marcas de agua de tus imágenes generadas',
    loginRequired: 'Inicio de Sesión Requerido',
    loginToAccessWatermarkRemoval: 'Por favor inicia sesión para acceder al servicio de eliminación de marca de agua',
    
    // General
    welcome: 'Bienvenido',
    hi: 'Hola',
    pro: 'PRO',
    worldClassAISolutions: 'Soluciones de IA de clase mundial para empresas. Transforma tu flujo de trabajo con inteligencia artificial de vanguardia.',
    exploreOurSuite: 'Explora nuestra completa suite de servicios de IA diseñados para resolver problemas del mundo real y mejorar tu productividad.',
    serviceCategories: 'Categorías de Servicio',
    imageProcessing: 'Procesamiento de Imágenes',
    advancedTools: 'Herramientas avanzadas para mejora de imágenes, eliminación de fondo y manipulación.',
    contentGeneration: 'Generación de Contenido',
    aiPoweredTools: 'Herramientas impulsadas por IA para crear contenido y documentos profesionales.',
    designTools: 'Herramientas de Diseño',
    creativeTools: 'Herramientas creativas para diseñadores y artistas para mejorar sus flujos de trabajo.',
    readyToGetStarted: '¿Listo para Empezar?',
    joinThousands: 'Únete a miles de profesionales que utilizan nuestra plataforma de IA para mejorar su productividad y creatividad.',
    createFreeAccount: 'Crear Cuenta Gratis',
    viewPricing: 'Ver Precios',
    explore: 'Explorar →',
    allServices: 'Todos los Servicios',
    accounts: 'Cuenta',
    dashboardLink: 'Panel',
    apiKeys: 'Claves de API',
    pricingLink: 'Precios',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    security: 'Seguridad',
    compliance: 'Cumplimiento',
    allRightsReserved: 'Todos los derechos reservados.',
    
    // Authentication
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    signInToYourAccount: 'Inicia sesión en tu cuenta',
    dontHaveAnAccount: '¿No tienes una cuenta?',
    signUpHere: 'Regístrate aquí',
    alreadyHaveAnAccount: '¿Ya tienes una cuenta?',
    signInHere: 'Inicia sesión aquí',
    registerForFree: 'Registrarse Gratis',
    forgotPassword: '¿Olvidaste tu contraseña?',
    rememberMe: 'Recuérdame',
    signingIn: 'Iniciando sesión...',
    newToPlatform: '¿Nuevo en AI Background Removal?',
    createAccount: 'Crear una nueva cuenta',
    iAgreeToThe: 'Acepto los',
    and: 'y',
    termsAndConditions: 'Términos y Condiciones',
    creatingAccount: 'Creando cuenta...',
    chooseFile: 'Elegir archivo',
    whatShouldAIDo: '¿Qué debe hacer la IA?',
    removeBackgroundExample: 'Eliminar el fondo',
    changeBackgroundExample: 'Cambiar fondo a azul',
    enhanceImageExample: 'Mejorar la calidad de la imagen',
    vibrantColorsExample: 'Hacer los colores más vibrantes',
    changeBackgroundAndEnhanceExample: 'Cambiar fondo a #FF6B6B y mejorar',
    instructionPlaceholder: "Ejemplos: 'Eliminar el fondo', 'Cambiar fondo a azul', 'Hacer que la persona use una camisa roja', 'Mejorar la calidad de la imagen', 'Hacer los colores más vibrantes', 'Cambiar la camisa de la persona a rojo y el fondo a verde', etc.",
    instructionDescription: 'Describe lo que quieres hacer con la imagen en lenguaje natural. La IA analizará tu solicitud y aplicará el procesamiento apropiado. Puedes solicitar múltiples operaciones en una sola instrucción.',
    processWithAI: 'Procesar con IA',
    reset: 'Reiniciar',
    processingWithAI: 'Procesando tu imagen con IA...',
    original: 'Original',
    processed: 'Procesado',
    downloadResult: 'Descargar Resultado',
    allImages: 'Todas las Imágenes',
    backgroundRemoval: 'Eliminación de Fondo',
    backgroundChange: 'Cambio de Fondo',
    backgroundReplace: 'Reemplazo de Fondo',
    clothesChange: 'Cambio de Ropa',
    clothesReplace: 'Reemplazo de Ropa',
    saveYourWork: 'Guarda Tu Trabajo',
    createAccountToSave: 'Crea una cuenta para guardar y acceder a tus imágenes procesadas en cualquier momento',
    noImagesFound: 'No se encontraron imágenes',
    processImagesToSee: 'Procesa algunas imágenes para que aparezcan aquí',
    tryServicesToSee: 'Prueba nuestros servicios para ver tus resultados aquí',
    tryOurServices: 'Prueba Nuestros Servicios',
    readyToProcess: '¿Listo para Procesar Tus Imágenes?',
    startUsingAIPowered: '¡Comienza a usar nuestras herramientas de procesamiento de imágenes impulsadas por IA hoy mismo: no se requiere cuenta para comenzar!',
    startProcessing: 'Comenzar a Procesar',
    pricing: 'Precios',
    free: 'Gratis',
    forever: 'para siempre',
    perfectForGettingStarted: 'Perfecto para comenzar con nuestra plataforma de IA',
    basicImageProcessing: 'Procesamiento Básico de Imágenes',
    apiCallsPerDay: 'Llamadas a la API/día',
    standardSupport: 'Soporte Estándar',
    proFeatures: 'Funciones Pro',
    prioritySupport: 'Soporte Prioritario',
    unlimitedApiCalls: 'Llamadas a la API ilimitadas',
    getStarted: 'Empezar',
    pro: 'Pro',
    perMonth: '/mes',
    idealForProfessionals: 'Ideal para profesionales y equipos pequeños',
    allFreeFeatures: 'Todas las Funciones Gratuitas',
    advancedImageProcessing: 'Procesamiento Avanzado de Imágenes',
    aiUpscaler: 'Mejorador de IA',
    faceDetection: 'Detección Facial',
    objectDetection: 'Detección de Objetos',
    metadataAnalyzer: 'Analizador de Metadatos',
    formatConverter: 'Convertidor de Formato',
    upgradeToPro: 'Actualizar a Pro',
    enterprise: 'Empresarial',
    custom: 'Personalizado',
    forLargeTeams: 'Para equipos grandes y requisitos personalizados',
    allProFeatures: 'Todas las Funciones Pro',
    customApiLimits: 'Límites de API personalizados',
    dedicatedSupport: 'Soporte Dedicado',
    customIntegrations: 'Integraciones Personalizadas',
    slaGuarantee: 'Garantía de SLA',
    teamManagement: 'Gestión de Equipos',
    advancedAnalytics: 'Análisis Avanzado',
    whiteLabelOptions: 'Opciones de marca blanca',
    customAiModels: 'Modelos de IA Personalizados',
    contactSales: 'Contactar Ventas',
    mostPopular: 'MÁS POPULAR',
    featureComparison: 'Comparación de Funciones',
    feature: 'Función',
    unlimited: 'Ilimitado',
    limited: 'Limitado',
    readyToTransform: '¿Listo para Transformar Tu Flujo de Trabajo?',
    startFreeTrial: 'Comenzar Prueba Gratuita',
    exploreServices: 'Explorar Servicios',
    brandName: 'Hintergrund entfernen',

    // Buttons
    submit: 'Enviar',
    upload: 'Subir',
    process: 'Procesar',
    cancel: 'Cancelar',
    
    // Errors
    error: 'Error',
    success: 'Éxito',
    pleaseTryAgain: 'Por favor intenta de nuevo',
    
    // Footer
    servicesFooter: 'Servicios',
    legal: 'Legal',
    accountFooter: 'Cuenta',

    // Language
    language: 'Idioma',

    // Watermark removal
    watermarkRemoval: 'Eliminación de Marca de Agua',
    removeWatermarkDescription: 'Elimina marcas de agua de tus imágenes generadas',
    loginRequired: 'Inicio de Sesión Requerido',
    loginToAccessWatermarkRemoval: 'Por favor inicia sesión para acceder al servicio de eliminación de marca de agua',
    uploadImage: 'Subir Imagen',
    chooseDifferentImage: 'Elegir una imagen diferente',
    dragAndDrop: 'Arrastra y suelta tu imagen aquí',
    maxFileSize: 'Tamaño máximo de archivo: 10MB. Formatos soportados: JPG, PNG, GIF',
    browseFiles: 'Explorar Archivos',
    processing: 'Procesando...',
    download: 'Descargar',
    newImage: 'Nueva Imagen',
    result: 'Resultado',
    watermarkSuccessfullyRemoved: '¡Marca de agua eliminada con éxito!',
    processedImageWillAppear: 'La imagen procesada aparecerá aquí',
    processImageToSeeResult: 'Procesa una imagen para ver el resultado aquí',
    howItWorks: 'Cómo funciona',
    uploadImageDescription: 'Sube tu imagen con marca de agua',
    removeWatermarkDescription: 'Haz clic en el botón de eliminar marca de agua',
    downloadResultDescription: 'Descarga tu imagen sin marca de agua',
    fileTooLarge: 'El archivo es demasiado grande. El tamaño máximo es 10MB.',
    invalidFileType: 'Tipo de archivo inválido. Por favor sube un archivo de imagen.',
    pleaseSelectFile: 'Por favor selecciona un archivo para procesar.',
    errorProcessingImage: 'Error al procesar la imagen. Por favor intenta de nuevo.',

    // Additional translations for homepage
    before: 'Antes',
    after: 'Después',
    beforeAfterComparison: 'Comparación antes y después',
    whyChoosePlatform: '¿Por qué elegir nuestra plataforma de IA?',
    lightningFastProcessing: 'Procesamiento ultrarrápido',
    getResultsInSeconds: 'Obtenga resultados en segundos con nuestros algoritmos de IA optimizados',
    enterpriseSecurity: 'Seguridad empresarial',
    militaryGradeEncryption: 'Cifrado de grado militar mantiene sus datos seguros',
    accuracy: 'Precisión del 99.9%',
    precisionAI: 'La tecnología de IA de precisión entrega resultados de calidad profesional',
    support: 'Soporte',
  },
  de: {
    // Navigation
    home: 'Startseite',
    services: 'Dienste',
    pricing: 'Preise',
    dashboard: 'Dashboard',
    login: 'Anmelden',
    signUp: 'Registrieren',
    logout: 'Abmelden',
    gallery: 'Galerie',
    autoAgent: 'Agent',
    apiDashboard: 'API',

    // Services
    imageProcessingSuite: 'Hintergrund jetzt ändern',
    aiCvGenerator: 'KI Lebenslauf-Generator',
    colorPaletteGenerator: 'Farbpaletten-Generator',
    objectDetectionTool: 'Objekterkennung-Tool',
    imageUpscaler: 'Bild-Scaler',
    backgroundBlur: 'Hintergrundunschärfe',
    imageEditingSuite: 'Bildbearbeitungs-Suite',
    faceDetection: 'Gesichtserkennung & Zuschneiden',
    imageMetadataAnalyzer: 'Bild-Metadaten-Analysator',
    formatConverter: 'Format-Konverter',
    aiAutoAgent: 'KI Auto-Agent',
    
    // Service descriptions
    advancedBackgroundRemoval: 'Fortgeschrittene Werkzeuge zur Hintergrundentfernung, Verbesserung und Manipulation',
    createProfessionalCvs: 'Erstellen Sie professionelle Lebensläufe mit KI-gestützter Inhaltserstellung',
    extractAndGenerate: 'Extrahieren und generieren Sie schöne Farbpaletten aus Bildern',
    identifyAndLocate: 'Identifizieren und lokalisieren Sie Objekte in Bildern mit Präzision',
    enhanceImageResolution: 'Verbessern Sie die Bildauflösung mit KI-gestütztem Upscaling',
    applyProfessionalPortrait: 'Wenden Sie professionelle Porträt-Modus-Effekte auf Bilder an',
    advancedImageEditing: 'Fortgeschrittene Bildbearbeitungstools einschließlich Zuschneiden, Unschärfen, Drehen und Spiegeln',
    detectFacesAndAutomatically: 'Erkennen Sie Gesichter und schneiden Sie diese automatisch auf optimale Dimensionen zu',
    extractDetailedExif: 'Extrahieren Sie detaillierte EXIF-Daten und Bildinformationen',
    convertBetweenImage: 'Konvertieren Sie zwischen Bildformaten mit intelligenter Komprimierung',
    uploadImageAndTell: 'Laden Sie ein Bild hoch und sagen Sie der KI, was zu tun ist - unser intelligenter Agent verarbeitet Ihre Anfrage automatisch',
    
    // Watermark removal
    watermarkRemoval: 'Wasserzeichenentfernung',
    removeWatermark: 'Hintergrund entfernen',
    removeWatermarkDescription: 'Entfernen Sie Wasserzeichen aus Ihren generierten Bildern',
    loginRequired: 'Anmeldung erforderlich',
    loginToAccessWatermarkRemoval: 'Bitte melden Sie sich an, um auf den Wasserzeichenentfernungsdienst zuzugreifen',
    
    // General
    welcome: 'Willkommen',
    hi: 'Hallo',
    pro: 'PRO',
    worldClassAISolutions: 'Weltklasse KI-Lösungen für Unternehmen. Transformieren Sie Ihren Arbeitsablauf mit modernster künstlicher Intelligenz.',
    exploreOurSuite: 'Entdecken Sie unsere umfassende Suite an KI-Diensten, die darauf ausgelegt sind, reale Probleme zu lösen und Ihre Produktivität zu steigern.',
    serviceCategories: 'Dienstleistungskategorien',
    imageProcessing: 'Bildverarbeitung',
    advancedTools: 'Fortgeschrittene Tools zur Bildverbesserung, Hintergrundentfernung und Manipulation.',
    contentGeneration: 'Inhaltsgenerierung',
    aiPoweredTools: 'KI-gestützte Tools zur Erstellung professioneller Inhalte und Dokumente.',
    designTools: 'Design-Tools',
    creativeTools: 'Kreative Tools für Designer und Künstler, um ihre Arbeitsabläufe zu verbessern.',
    readyToGetStarted: 'Bereit loszulegen?',
    joinThousands: 'Tausende von Fachleuten nutzen unsere KI-Plattform, um Produktivität und Kreativität zu steigern.',
    createFreeAccount: 'Kostenloses Konto erstellen',
    viewPricing: 'Preise ansehen',
    explore: 'Entdecken →',
    allServices: 'Alle Dienste',
    accounts: 'Konto',
    dashboardLink: 'Dashboard',
    apiKeys: 'API-Schlüssel',
    pricingLink: 'Preise',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    security: 'Sicherheit',
    compliance: 'Compliance',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    
    // Authentication
    email: 'E-Mail',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    firstName: 'Vorname',
    lastName: 'Nachname',
    signInToYourAccount: 'Melden Sie sich bei Ihrem Konto an',
    dontHaveAnAccount: 'Sie haben noch kein Konto?',
    signUpHere: 'Hier registrieren',
    alreadyHaveAnAccount: 'Sie haben bereits ein Konto?',
    signInHere: 'Hier anmelden',
    registerForFree: 'Kostenlos registrieren',
    forgotPassword: 'Passwort vergessen?',
    rememberMe: 'Angemeldet bleiben',
    signingIn: 'Anmeldung läuft...',
    newToPlatform: 'Neu bei AI Background Removal?',
    createAccount: 'Ein neues Konto erstellen',
    iAgreeToThe: 'Ich stimme den',
    and: 'und',
    termsAndConditions: 'Allgemeinen Geschäftsbedingungen',
    creatingAccount: 'Konto wird erstellt...',
    chooseFile: 'Datei auswählen',
    whatShouldAIDo: 'Was soll die KI tun?',
    removeBackgroundExample: 'Hintergrund entfernen',
    changeBackgroundExample: 'Hintergrund auf blau ändern',
    enhanceImageExample: 'Bildqualität verbessern',
    vibrantColorsExample: 'Farben lebendiger machen',
    changeBackgroundAndEnhanceExample: 'Hintergrund zu #FF6B6B ändern und verbessern',
    instructionPlaceholder: "Beispiele: 'Hintergrund entfernen', 'Hintergrund auf blau ändern', 'Person ein rotes Hemd anziehen', 'Bildqualität verbessern', 'Farben lebendiger machen', 'Hemd der Person rot und Hintergrund grün färben', etc.",
    instructionDescription: 'Beschreiben Sie in natürlicher Sprache, was Sie mit dem Bild tun möchten. Die KI analysiert Ihre Anfrage und wendet die entsprechende Verarbeitung an. Sie können mehrere Operationen in einer einzigen Anweisung anfordern.',
    processWithAI: 'Mit KI verarbeiten',
    reset: 'Zurücksetzen',
    processingWithAI: 'Ihr Bild wird mit KI verarbeitet...',
    original: 'Original',
    processed: 'Verarbeitet',
    downloadResult: 'Ergebnis herunterladen',
    allImages: 'Alle Bilder',
    backgroundRemoval: 'Hintergrundentfernung',
    backgroundChange: 'Hintergrundänderung',
    backgroundReplace: 'Hintergrundaustausch',
    clothesChange: 'Kleidungswechsel',
    clothesReplace: 'Kleidungsaustausch',
    saveYourWork: 'Speichern Sie Ihre Arbeit',
    createAccountToSave: 'Erstellen Sie ein Konto, um Ihre bearbeiteten Bilder jederzeit zu speichern und abzurufen',
    noImagesFound: 'Keine Bilder gefunden',
    processImagesToSee: 'Bearbeiten Sie einige Bilder, damit sie hier erscheinen',
    tryServicesToSee: 'Probieren Sie unsere Dienste aus, um Ihre Ergebnisse hier zu sehen',
    tryOurServices: 'Probieren Sie Unsere Dienste',
    readyToProcess: 'Bereit Ihre Bilder zu bearbeiten?',
    startUsingAIPowered: 'Beginnen Sie noch heute mit unseren KI-gestützten Bildbearbeitungstools - es ist kein Konto erforderlich, um zu starten!',
    startProcessing: 'Mit Bearbeitung Beginnen',
    pricing: 'Preise',
    free: 'Kostenlos',
    forever: 'für immer',
    perfectForGettingStarted: 'Perfekt, um mit unserer KI-Plattform zu beginnen',
    basicImageProcessing: 'Basis-Bildverarbeitung',
    apiCallsPerDay: 'API-Aufrufe/Tag',
    standardSupport: 'Standard-Support',
    proFeatures: 'Pro-Funktionen',
    prioritySupport: 'Priorisierter Support',
    unlimitedApiCalls: 'Unbegrenzte API-Aufrufe',
    getStarted: 'Loslegen',
    pro: 'Pro',
    perMonth: '/Monat',
    idealForProfessionals: 'Ideal für Fachleute und kleine Teams',
    allFreeFeatures: 'Alle kostenlosen Funktionen',
    advancedImageProcessing: 'Erweiterte Bildverarbeitung',
    aiUpscaler: 'KI-Scaler',
    faceDetection: 'Gesichtserkennung',
    objectDetection: 'Objekterkennung',
    metadataAnalyzer: 'Metadaten-Analysator',
    formatConverter: 'Format-Konverter',
    upgradeToPro: 'Auf Pro upgraden',
    enterprise: 'Enterprise',
    custom: 'Individuell',
    forLargeTeams: 'Für große Teams und individuelle Anforderungen',
    allProFeatures: 'Alle Pro-Funktionen',
    customApiLimits: 'Individuelle API-Limits',
    dedicatedSupport: 'Dedizierter Support',
    customIntegrations: 'Individuelle Integrationen',
    slaGuarantee: 'SLA-Garantie',
    teamManagement: 'Team-Management',
    advancedAnalytics: 'Erweiterte Analysen',
    whiteLabelOptions: 'White-Label-Optionen',
    customAiModels: 'Individuelle KI-Modelle',
    contactSales: 'Vertrieb kontaktieren',
    mostPopular: 'AM BELIEBTESTEN',
    featureComparison: 'Funktionsvergleich',
    feature: 'Funktion',
    unlimited: 'Unbegrenzt',
    limited: 'Begrenzt',
    readyToTransform: 'Bereit, Ihren Arbeitsablauf zu transformieren?',
    startFreeTrial: 'Kostenlose Testversion starten',
    exploreServices: 'Dienste erkunden',
    brandName: 'Hintergrund entfernen',

    // Buttons
    submit: 'Senden',
    upload: 'Hochladen',
    process: 'Verarbeiten',
    cancel: 'Abbrechen',
    
    // Errors
    error: 'Fehler',
    success: 'Erfolg',
    pleaseTryAgain: 'Bitte versuchen Sie es erneut',
    
    // Footer
    servicesFooter: 'Dienste',
    legal: 'Rechtliches',
    accountFooter: 'Konto',

    // Language
    language: 'Sprache',

    // Watermark removal
    watermarkRemoval: 'Wasserzeichenentfernung',
    removeWatermarkDescription: 'Entfernen Sie Wasserzeichen aus Ihren generierten Bildern',
    loginRequired: 'Anmeldung erforderlich',
    loginToAccessWatermarkRemoval: 'Bitte melden Sie sich an, um auf den Wasserzeichenentfernungsdienst zuzugreifen',
    uploadImage: 'Bild hochladen',
    chooseDifferentImage: 'Anderes Bild wählen',
    dragAndDrop: 'Ziehen Sie Ihr Bild hierher',
    maxFileSize: 'Maximale Dateigröße: 10MB. Unterstützte Formate: JPG, PNG, GIF',
    browseFiles: 'Dateien durchsuchen',
    processing: 'Verarbeitung...',
    download: 'Herunterladen',
    newImage: 'Neues Bild',
    result: 'Ergebnis',
    watermarkSuccessfullyRemoved: 'Wasserzeichen erfolgreich entfernt!',
    processedImageWillAppear: 'Verarbeitetes Bild wird hier angezeigt',
    processImageToSeeResult: 'Verarbeiten Sie ein Bild, um das Ergebnis hier zu sehen',
    howItWorks: 'So funktioniert es',
    uploadImageDescription: 'Laden Sie Ihr Bild mit Wasserzeichen hoch',
    removeWatermarkDescription: 'Klicken Sie auf die Schaltfläche zum Entfernen des Wasserzeichens',
    downloadResultDescription: 'Laden Sie Ihr wasserzeichenfreies Bild herunter',
    fileTooLarge: 'Datei ist zu groß. Maximale Größe beträgt 10MB.',
    invalidFileType: 'Ungültiger Dateityp. Bitte laden Sie eine Bilddatei hoch.',
    pleaseSelectFile: 'Bitte wählen Sie eine Datei zum Verarbeiten aus.',
    errorProcessingImage: 'Fehler beim Verarbeiten des Bildes. Bitte versuchen Sie es erneut.',

    // Additional translations for homepage
    before: 'Vorher',
    after: 'Nachher',
    beforeAfterComparison: 'Vorher-Nachher-Vergleich',
    whyChoosePlatform: 'Warum unsere KI-Plattform wählen?',
    lightningFastProcessing: 'Blitzschnelle Verarbeitung',
    getResultsInSeconds: 'Erhalten Sie Ergebnisse in Sekunden mit unseren optimierten KI-Algorithmen',
    enterpriseSecurity: 'Unternehmenssicherheit',
    militaryGradeEncryption: 'Militärverschlüsselung schützt Ihre Daten',
    accuracy: '99,9 % Genauigkeit',
    precisionAI: 'Präzisions-KI-Technologie liefert professionelle Ergebnisse',
    support: 'Support',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get language from localStorage or default to 'de' (German)
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'de';
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const translation = translations[language]?.[key];
    return translation || key; // Fallback to the key if translation is not found
  };

  const value = {
    language,
    setLanguage,
    t,
    availableLanguages: ['en', 'es', 'de']
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};